'use client'

import { CacheProvider } from '@chakra-ui/next-js'
import { ChakraProvider } from '@chakra-ui/react'

import { Inter } from "next/font/google";
import Navbar from "@/Layouts/Navbar";
import Footer from "@/Layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Digital Monkeys",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer/>
          </body>
        
      </html>
    </>
  );
}
