import { Inter } from "next/font/google";
import Navbar from "@/Layouts/Navbar";
import Footer from "@/Layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digital Monkeys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <nav>
          <Navbar />
        </nav>
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
